name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest app/test_app.py

    - name: Build Docker image
      run: |
        docker build -t soumyasekhardey/ansible-app:latest .

    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push soumyasekhardey/ansible-app:latest

  deploy:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up dynamic inventory
      run: |
        export EC2_PUBLIC_IP=${{ secrets.EC2_PUBLIC_IP }}
        envsubst < ansible/inventory.template > ansible/inventory

    - name: Write private key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ./ansible/id_rsa
        chmod 600 ./ansible/id_rsa

    - name: Run Ansible playbook
      uses: dawidd6/action-ansible-playbook@v3
      with:
        playbook: ansible/playbook.yml
        #inventory: ansible/inventory
        #key: ${{ secrets.EC2_SSH_KEY }}
        options: |
          --extra-vars "docker_image=soumyasekhardey/ansible-app:latest"